name: Backend Docker AppNode Mysql NestJs

on:
  push:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir containers com Docker Compose
        run: docker compose -f ./docker-compose.yml up -d mysqldb_prod node_prod
        
      - name: Aguardando iniciar Mysql
        run: |          
          sleep 15

      - name: Executar testes unitarios
        run: docker compose exec -T node_prod npm run test

      - name: Executar testes end-to-end
        run: docker compose exec -T node_prod npm run test:e2e

      - name: Finalizar containers
        run: docker compose down
